
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/movie-api?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

server:
  port: 5000
